"""Serialise scan results into run-context.json blocks.

Each helper turns one scan result (accretion, structure drift, doc staleness,
liveness, coverage, the keyhole signals) into the block shape the report,
gate and anomaly detector read, degrading to an explicit unavailable block
rather than a false negative. No helper runs a scan of its own except
``attach_structure_drift``, which runs the Tier 0 ownership check.
"""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path
from typing import Any

from lib.generated_files import matches_generated_name
from lib.scan_registry import safe as _safe
from lib.structure_drift import SEAM_ALLOWLIST, detect_path_existence_drift


# Cap on accretion files carried into run-context.json. The scanner measures
# every file; the run-context list keeps only the worst few that also score in
# the top complexity/size band, so a growing-but-simple file never earns a line.
MAX_ACCRETION_FILES = 12


def excluded_generated(complexity_stats: dict[str, Any]) -> list[dict[str, str]]:
    """The stats file's ``excluded_generated`` list, keeping well-formed rows.

    Each row is ``{"path", "reason"}`` with non-empty strings; anything else
    (an older stats file without the key, a malformed row) is dropped, so the
    run-context key is always a list.
    """
    rows = complexity_stats.get("excluded_generated")
    if not isinstance(rows, list):
        return []
    return [
        {"path": r["path"], "reason": r["reason"]}
        for r in rows
        if isinstance(r, dict)
        and isinstance(r.get("path"), str) and r["path"]
        and isinstance(r.get("reason"), str) and r["reason"]
    ]


def generated_exclusion(complexity_stats: dict[str, Any]) -> Callable[[str], bool]:
    """Predicate: is a path excluded as generated by this run?

    True for a path named in the stats file's ``excluded_generated`` list
    (content sniff) or matching a generated-name glob (silent, so never listed).
    """
    listed = {r["path"] for r in excluded_generated(complexity_stats)}
    return lambda path: path in listed or matches_generated_name(path)


def _top_band_paths(complexity_stats: dict[str, Any]) -> set[str]:
    """Paths already in the top complexity/size band of this run's stats.

    Union of the three ranked top-N lists (``top_hotspots``/``top_complex``/
    ``top_large``). Accretion is only surfaced for a file already in this set:
    a growing file that scores low on complexity *and* size isn't a hotspot, so
    flagging its growth would be noise. Mirrors lib.keyhole_signals._paths_from_stats.
    """
    paths: set[str] = set()
    for key in ("top_hotspots", "top_complex", "top_large"):
        for entry in complexity_stats.get(key) or []:
            path = entry.get("path")
            if path:
                paths.add(path)
    return paths


def accretion_block(scan: Any, complexity_stats: dict[str, Any]) -> dict[str, Any]:
    """Serialize an AccretionScan into the run-context ``accretion_ratchet`` block.

    On an unavailable scan, emits the same shape with an empty file list and the
    scan's reason (graceful degradation - a failed scan is never read as "no
    accretion"). On success, the flagged files are filtered to those already in
    the top complexity/size band (the noise budget), sorted by net additions
    descending with a path tie-break for a total, deterministic order, and capped
    at MAX_ACCRETION_FILES.
    """
    block: dict[str, Any] = {
        "available": scan.available,
        "reason": scan.reason,
        "reliable": scan.reliable,
        "deletion_fraction_threshold": scan.deletion_fraction_threshold,
        "files": [],
    }
    if not scan.available:
        return block

    band = _top_band_paths(complexity_stats)
    in_band = [f for f in scan.files if f.path in band]
    # The scan already sorts by (-net_additions, path); re-sort defensively so
    # the serialized order is a total, clone-independent order regardless of the
    # filtered subset's incoming order.
    in_band.sort(key=lambda f: (-f.net_additions, f.path))
    block["total_in_band"] = len(in_band)
    block["files"] = [f.to_dict() for f in in_band[:MAX_ACCRETION_FILES]]
    return block


def accretion_lookup(scan: Any) -> dict[str, dict[str, Any]]:
    """O(1) ``{path: accretion_info}`` for the hotspot pages, from one scan.

    Each entry is the serialized AccretionFile plus the scan-wide ``reliable``
    flag, so a hotspot page can name a file's growth profile and disclaim it on
    degenerate history without re-deriving anything. Returns ``{}`` when the
    scan was unavailable - the hotspot loop then writes pages with no growth
    line (graceful degradation; the scan never gates page generation).
    """
    if not scan.available:
        return {}
    lookup: dict[str, dict[str, Any]] = {}
    for af in scan.files:
        entry = af.to_dict()
        entry["reliable"] = scan.reliable
        lookup[af.path] = entry
    return lookup


# The six Tier 1 grouping-disagreement counts, in a fixed order so the
# run-context tier_1 sub-block is deterministic regardless of dict iteration.
_TIER1_DISAGREEMENT_KEYS = (
    "human_grouped_static_splits",
    "human_split_static_fuses",
    "human_grouped_never_cochange",
    "human_split_but_cochange",
    "human_static_agree",
    "human_cochange_agree",
)


def _structure_drift_block(
    repo_root: Path, tier_1: dict[str, Any],
) -> dict[str, Any] | None:
    """Build the run-context ``structure_drift`` block (Tier 0 + Tier 1).

    Tier 0 (``detect_path_existence_drift``) is the zero-threshold cut: declared
    ownership patterns matching no tracked file. It runs whenever an ownership
    map exists; when none does it degrades to ``available: False`` and the whole
    block is omitted (the caller drops a ``None``), keeping non-owned repos'
    run-context byte-stable.

    ``tier_1`` is the grouping-disagreement result ``keyhole_signals.integrate``
    already computed from the behaviour block's co-change pairs (no second
    ``git log`` parse, no double computation) - either the six disagreement
    counts or an ``available: False`` marker when the static import graph was
    unavailable or no ownership map existed. The seam allowlist was applied
    inside the detector, so the counts here are already post-allowlist.

    Returns ``None`` when Tier 0 is unavailable (no ownership map) - a graceful,
    half-block-free omission. Otherwise returns a JSON-serialisable block whose
    ``tier_0`` always carries data and whose ``tier_1`` is either the six
    disagreement counts or ``{"available": False}``.
    """
    tier_0 = detect_path_existence_drift(repo_root)
    if not tier_0.get("available"):
        return None  # no ownership map - omit the block entirely

    block: dict[str, Any] = {
        "tier_0": {
            "available": True,
            "empty_ownership_patterns": tier_0["empty_ownership_patterns"],
            "total_patterns": tier_0["total_patterns"],
            "matched_patterns": tier_0["matched_patterns"],
        },
    }

    if not tier_1.get("available"):
        block["tier_1"] = {"available": False}
        return block

    tier_1_block: dict[str, Any] = {"available": True}
    for key in _TIER1_DISAGREEMENT_KEYS:
        tier_1_block[f"{key}_count"] = tier_1.get(f"{key}_count", 0)
    tier_1_block["seam_allowlist_applied"] = True
    tier_1_block["allowlist_pairs_count"] = len(SEAM_ALLOWLIST)
    block["tier_1"] = tier_1_block
    return block


def attach_structure_drift(
    ctx: dict[str, Any], repo_root: Path, tier_1: dict[str, Any],
) -> None:
    """Attach the structure_drift block to ctx, or omit it on a graceful degrade.

    Builds the block via :func:`_structure_drift_block` (Tier 0 + the supplied
    Tier 1 result) under :func:`_safe`. Attaches only a real block (one carrying
    a ``tier_0``): the no-ownership-map path returns ``None`` and a scan failure
    returns ``_safe``'s degrade dict (no ``tier_0``); both omit the block rather
    than emit a half-block, keeping the contract that absence means "nothing to
    drift against / not assessed", never "no drift".
    """
    block = _safe(
        "structure_drift",
        lambda: _structure_drift_block(repo_root, tier_1),
    )
    if isinstance(block, dict) and "tier_0" in block:
        ctx["structure_drift"] = block


def build_stale_hubs(
    doc_graph: dict[str, Any], doc_staleness: dict[str, Any],
) -> list[dict[str, Any]]:
    """Centrality x staleness - the priority Layer 0 signal.

    A stale *hub* (high PageRank) is the most dangerous lying map: everything
    routes through it. We join the doc graph's central docs with their
    staleness ratio so a stale hub surfaces as a top finding.

    Each hub carries the underlying `subject_method` + a `confidence` flag.
    `subject_method == "repo-baseline"` means the ratio is computed against
    repo-wide churn (no derivable subject), so the priority composite shares
    a denominator across every baseline entry - confidence on those is "low".
    The sort halves the priority of low-confidence entries so a precise-subject
    hub at half the raw priority of a baseline one still outranks it.
    """
    if not doc_graph.get("available") or not doc_staleness.get("available"):
        return []
    staleness_by_path = {d["path"]: d for d in doc_staleness.get("docs", [])}
    hubs: list[dict[str, Any]] = []
    for hub in doc_graph.get("hubs", []):
        s = staleness_by_path.get(hub["path"])
        if s is None:
            continue
        priority = round(hub["pagerank"] * s["ratio"], 3)
        confidence = s.get("confidence", "high")
        hubs.append({
            "path": hub["path"],
            "pagerank": hub["pagerank"],
            "last_commit_days": s["last_commit_days"],
            "code_churn_in_window": s["code_churn_in_window"],
            "ratio": s["ratio"],
            "subject_method": s.get("subject_method"),
            "confidence": confidence,
            "priority": priority,
        })
    return sorted(
        hubs,
        key=lambda h: -(h["priority"] * (0.5 if h["confidence"] == "low" else 1.0)),
    )


def dict_or(value: Any, default: Any) -> Any:
    """``value`` when it is a dict (a scan block), else ``default``."""
    return value if isinstance(value, dict) else default


def doc_to_code_edges(doc_graph: dict[str, Any]) -> list[Any]:
    """The doc graph's doc->code edges, empty when the graph is unavailable."""
    return (doc_graph.get("doc_to_code_edges", [])
            if doc_graph.get("available") else [])


def attach_liveness_blocks(ctx: dict[str, Any], liveness: Any) -> None:
    """Set dead_code / observability, plus the capability keys when detected."""
    # When the scan failed, preserve failure semantics: a failed scan must not be
    # read as "no observability" (rung 0) - that would mis-score Layer 1 Missing
    # when the truth is "not assessed". Carry the reason instead.
    liveness_ok = isinstance(liveness, dict) and "dead_code" in liveness
    reason = (liveness.get("reason", "liveness scan unavailable")
              if isinstance(liveness, dict) else "liveness scan unavailable")
    ctx["dead_code"] = (
        liveness["dead_code"] if liveness_ok
        else {"available": False, "candidate_count": 0, "candidates": [],
              "tools": [], "reason": reason}
    )
    ctx["observability"] = (
        liveness["observability"] if liveness_ok
        else {"rung": None, "available": False, "reason": reason,
              "instrumented": {"present": False, "signals": []},
              "discoverable": {"present": False, "signals": []},
              "reachable": {"present": False, "signals": []}}
    )
    # Capability-driven JVM offers (issue #113): present only when a Maven/Gradle
    # project is detected, so non-JVM repos carry no extra key (the run-context
    # baseline stays stable). Names each unserved capability + a candidate tool
    # (honest-degrade) and the liveness run/install-consent offer the Step 2
    # offer-layer turns into an AskUserQuestion.
    if liveness_ok and isinstance(liveness.get("jvm_capabilities"), dict):
        ctx["capability_offers"] = liveness["jvm_capabilities"]
    # Non-JVM capability entries keyed by language (issue #352), present only
    # when a language is detected; capability_offers stays JVM-only.
    if liveness_ok and isinstance(liveness.get("dart_capabilities"), dict):
        ctx["language_capabilities"] = {
            "dart": liveness["dart_capabilities"]["capabilities"]}


def coverage_report_block(cov_detect: Any, coverage_data: Any) -> dict[str, Any]:
    """Provenance of the coverage report read (or "none found")."""
    if cov_detect:
        return {
            "available": True,
            "source": cov_detect["source"],
            "format": cov_detect["format"],
            "parsed": coverage_data is not None,
        }
    return {"available": False, "source": "none found"}


def attach_keyhole_blocks(ctx: dict[str, Any], keyhole: dict[str, Any]) -> None:
    """Copy the keyhole signal blocks and report-skeleton products into ctx."""
    ctx["structure"] = keyhole["structure"]
    ctx["behaviour"] = keyhole["behaviour"]
    ctx["documentation"] = keyhole["documentation"]
    ctx["understanding"] = keyhole["understanding"]
    ctx["runtime"] = keyhole["runtime"]
    ctx["derived_findings"] = keyhole["derived_findings"]
    ctx["attention"] = keyhole["attention"]
    ctx["attention_low_signal"] = keyhole["attention_low_signal"]
    # Deterministic report-skeleton products (assess-dogfooded Part 1): the
    # pre-rendered findings section the LLM copies verbatim, the keyhole
    # readiness summary reported alongside (never merged into) the 0-8 score, and
    # the mandatory attention-derived Top-3 actions.
    ctx["findings_markdown"] = keyhole["findings_markdown"]
    ctx["keyhole_summary"] = keyhole["keyhole_summary"]
    ctx["prescribed_actions"] = keyhole["prescribed_actions"]


def attach_exclusion_disclosures(
    ctx: dict[str, Any], keyhole: dict[str, Any],
    extra_exclude_dirs: Any, extra_exclude_patterns: Any,
) -> None:
    """Set the config / archive / dead-path finding-exclusion disclosure blocks."""
    # Config-exclusion disclosure: config excludes silently drop paths from every
    # scan, so a finding suppressed by an exclude must be counted and named rather
    # than vanish. keyhole_signals filtered the excluded finding paths; this block
    # records the active excludes alongside the paths that would otherwise have
    # been findings, so the gate and report can surface the suppression.
    excluded_finding_paths = keyhole.get("excluded_finding_paths", [])
    ctx["excluded_by_config"] = {
        "dirs": sorted(extra_exclude_dirs),
        "patterns": list(extra_exclude_patterns),
        "affected_finding_paths": excluded_finding_paths,
        "count": len(excluded_finding_paths),
    }
    # Archive disclosure: paths under archive/, archived/ or attic/ are kept out
    # of attention and prescribed_actions; this block names and counts them so
    # the exclusion is visible. Mirrors excluded_by_config's path/count shape.
    archived_finding_paths = keyhole.get("archived_finding_paths", [])
    ctx["excluded_as_archive"] = {
        "affected_finding_paths": archived_finding_paths,
        "count": len(archived_finding_paths),
    }
    # Dead-path disclosure: a git-history finding path that no longer exists
    # (deleted, with no rename to follow) is dropped from the findings,
    # attention, prescribed actions and markdown; this block names and counts it.
    # rename_map_complete False means git history could not be read for renames:
    # nothing was folded or pruned, and a finding may still name an old path.
    pruned_finding_paths = keyhole.get("pruned_finding_paths", [])
    ctx["pruned_finding_paths"] = {
        "paths": pruned_finding_paths,
        "count": len(pruned_finding_paths),
        "rename_map_complete": keyhole.get("rename_map_complete", True),
    }
