"""Content-based detection of files that are not hand-written source.

Filename globs (``EXCLUDE_FILE_PATTERNS`` in ``complexity-treemap.py``) miss
machine-written files with ordinary names, such as a schema dump or a font
embedded as a base64 string. (This docstring keeps the markers below out of its
first lines, or the sniff would exclude this module.) Two content checks catch
them:

- **Header sniff** (reason ``generated-header``): the first
  ``HEADER_SNIFF_LINES`` lines carry a conventional generator marker (the
  Go / protobuf convention most generators follow). A marker further down the
  file is ignored, so a hand-written comment on line 200 never excludes it.
- **Long lines** (reason ``long-lines``): the average line length exceeds
  ``LONG_LINE_THRESHOLD`` characters, the shape of a base64 or minified payload.

Both are pure stdlib and read at most the head of the file (header) or the
whole file once (long lines). An unreadable file is never excluded.
"""
from __future__ import annotations

import re
from pathlib import Path

HEADER_SNIFF_LINES = 5

# Bytes read for the header sniff. Enough for five ordinary lines; a minified
# first line longer than this is left to the long-line check.
_HEADER_READ_BYTES = 64 * 1024

# Case-insensitive markers. "Code generated by ... DO NOT EDIT" (the Go
# convention) is covered by the bare "do not edit" alternative, and
# "This file is auto-generated" by "auto-generated" (also spaced or unhyphenated).
_HEADER_MARKERS = re.compile(
    r"generated file|do not edit|@generated|auto[-\s]?generated",
    re.IGNORECASE,
)

# Average characters per line above which a file is a payload, not source.
# Calibrated against real files: a Playwright HTML report averages ~16,000 and
# a base64 font module ~20,000, while a JSONL fixture averages 296 and a
# hand-built HTML explainer page 3,817. 1,000 sits between the two groups.
LONG_LINE_THRESHOLD = 1000

REASON_HEADER = "generated-header"
REASON_LONG_LINES = "long-lines"


def has_generated_header(path: Path, lines: int = HEADER_SNIFF_LINES) -> bool:
    """True when one of the first ``lines`` lines carries a generator marker."""
    try:
        with path.open("rb") as fh:
            head = fh.read(_HEADER_READ_BYTES)
    except OSError:
        return False
    text = head.decode("utf-8", errors="ignore")
    return any(_HEADER_MARKERS.search(line) for line in text.splitlines()[:lines])


def average_line_length(path: Path) -> float:
    """Mean characters per line; 0.0 for an empty or unreadable file.

    A final line without a trailing newline still counts as a line.
    """
    try:
        data = path.read_bytes()
    except OSError:
        return 0.0
    if not data:
        return 0.0
    line_count = data.count(b"\n") + (0 if data.endswith(b"\n") else 1)
    # Characters, not bytes: 600 CJK characters are ~1,800 UTF-8 bytes.
    return len(data.decode("utf-8", errors="ignore")) / line_count


def is_long_line_artifact(path: Path,
                          threshold: float = LONG_LINE_THRESHOLD) -> bool:
    """True when the file's average line length exceeds ``threshold``."""
    return average_line_length(path) > threshold


def generated_reason(path: Path) -> str | None:
    """The exclusion reason for ``path``, or None when it reads as source.

    The header sniff runs first, so a generated file with long lines reports
    ``generated-header``.
    """
    if has_generated_header(path):
        return REASON_HEADER
    if is_long_line_artifact(path):
        return REASON_LONG_LINES
    return None
