"""Content-based detection of files that are not hand-written source.

Filename globs (``EXCLUDE_FILE_PATTERNS`` in ``complexity-treemap.py``) miss
machine-written files with ordinary names, such as a schema dump or a font
embedded as a base64 string. Two content checks catch them:

- **Header sniff** (reason ``generated-header``): one of the first
  ``HEADER_SNIFF_LINES`` lines is a comment carrying a conventional generator
  marker (the Go / protobuf convention most generators follow). A marker
  further down the file is ignored, so a hand-written comment on line 200 never
  excludes it; so is a marker in prose (a docstring continuation line about
  codegen), because the line does not open with a comment leader.
- **Long lines** (reason ``long-lines``): the average line length over the
  first 1 MB exceeds ``LONG_LINE_THRESHOLD`` characters, the shape of a base64
  or minified payload.

Both are pure stdlib and read a bounded head of the file. An unreadable file is
never excluded.
"""
from __future__ import annotations

import fnmatch
import re
from pathlib import Path

HEADER_SNIFF_LINES = 5

# Upper bound on bytes the header sniff reads while collecting its first lines,
# the same bound the long-line check uses.
_HEADER_READ_BYTES = 1024 * 1024

# Case-insensitive markers. "Code generated by ... DO NOT EDIT" (the Go
# convention) is covered by the bare "do not edit" alternative, and
# "This file is auto-generated" by "auto-generated" (also spaced or unhyphenated).
_HEADER_MARKERS = re.compile(
    r"do not edit|@generated|auto[-\s]?generated",
    re.IGNORECASE,
)
# "GENERATED FILE" is common in prose ("writes the generated file"), so it
# counts only when it opens the comment body: `-- GENERATED FILE - ...`,
# `/* Generated file */`, `# === GENERATED FILE ===`.
_BANNER_PUNCTUATION = " \t-=*#/!<>"
_BANNER_MARKER = "generated file"

# A generator declaration is always a comment, so the marker line must open
# with a comment leader: # // -- /* <!-- ; % {- (* or a docstring quote. A bare
# `*` counts only when indented (a JSDoc / block-comment continuation), so a
# Markdown bullet at column 0 is not read as a comment. In Markdown, `#` opens
# a heading (prose), so only `<!--` counts there.
_COMMENT_LEADER = re.compile(
    r"""^(\s*(#|//|--|/\*|<!--|;|%|\{-|\(\*|"{3}|'{3})|\s+\*)"""
)
_MARKDOWN_COMMENT_LEADER = re.compile(r"^\s*<!--")
_MARKDOWN_SUFFIXES = {".md", ".mdx", ".markdown"}

# Bytes the long-line check averages over. The cap bounds IO and memory on
# large files; the average only has to separate payloads (~20,000 characters
# per line) from hand-written code, which a 1 MB sample does.
_LONG_LINE_READ_BYTES = 1024 * 1024

# Average characters per line above which a file is a payload, not source.
# Calibrated against real files: a Playwright HTML report averages ~16,000 and
# a base64 font module ~20,000; a JSONL fixture averages 296 and stays scored.
# A hand-built HTML explainer page with inline data (this repository's
# docs/huddle-explainer/visualization.html, ~3,800) is excluded on purpose:
# its bulk is the embedded payload, not code a reader maintains line by line.
# The threshold is kept above 296 and below that page's average.
LONG_LINE_THRESHOLD = 1000

# Filename globs for generated code, matched on the basename with no header
# needed. The treemap adds them to its EXCLUDE_FILE_PATTERNS; assess_core uses
# them to keep a file these globs newly exclude from being recorded as a
# graduated hotspot.
GENERATED_NAME_PATTERNS = ("*.generated.*", "*.gen.ts", "database.types.ts")

REASON_HEADER = "generated-header"
REASON_LONG_LINES = "long-lines"


def has_generated_header(path: Path, lines: int = HEADER_SNIFF_LINES) -> bool:
    """True when one of the first ``lines`` lines is a comment carrying a
    generator marker."""
    # Read line by line so a long early line cannot push lines 2-5 out of the
    # sample; the total read stays under _HEADER_READ_BYTES.
    head: list[bytes] = []
    remaining = _HEADER_READ_BYTES
    try:
        with path.open("rb") as fh:
            while len(head) < lines and remaining > 0:
                raw = fh.readline(remaining)
                if not raw:
                    break
                head.append(raw)
                remaining -= len(raw)
    except OSError:
        return False
    # A UTF-8 BOM (routine in .NET / PowerShell codegen) would defeat the
    # line-start anchor, so strip it before matching.
    text = b"".join(head).decode("utf-8", errors="ignore").removeprefix("\ufeff")
    leader = (_MARKDOWN_COMMENT_LEADER
              if path.suffix.lower() in _MARKDOWN_SUFFIXES else _COMMENT_LEADER)
    for line in text.splitlines()[:lines]:
        m = leader.match(line)
        if m is None:
            continue
        if _HEADER_MARKERS.search(line) is not None:
            return True
        body = line[m.end():].lstrip(_BANNER_PUNCTUATION).lower()
        if body.startswith(_BANNER_MARKER):
            return True
    return False


def average_line_length(path: Path) -> float:
    """Mean characters per line over the first 1 MB; 0.0 for an empty or
    unreadable file.

    A final line without a trailing newline still counts as a line.
    """
    try:
        with path.open("rb") as fh:
            data = fh.read(_LONG_LINE_READ_BYTES)
    except OSError:
        return 0.0
    if not data:
        return 0.0
    line_count = data.count(b"\n") + (0 if data.endswith(b"\n") else 1)
    # Characters, not bytes: 600 CJK characters are ~1,800 UTF-8 bytes.
    return len(data.decode("utf-8", errors="ignore")) / line_count


def is_long_line_artifact(path: Path,
                          threshold: float = LONG_LINE_THRESHOLD) -> bool:
    """True when the file's average line length exceeds ``threshold``.

    A file no larger than ``threshold`` bytes cannot qualify (characters <=
    bytes and there is at least one line), so it is rejected without a read.
    """
    try:
        if path.stat().st_size <= threshold:
            return False
    except OSError:
        return False
    return average_line_length(path) > threshold


def matches_generated_name(path: str | Path) -> bool:
    """True when the basename matches one of ``GENERATED_NAME_PATTERNS``."""
    name = Path(path).name
    return any(fnmatch.fnmatch(name, pat) for pat in GENERATED_NAME_PATTERNS)


def generated_reason(path: Path) -> str | None:
    """The exclusion reason for ``path``, or None when it reads as source.

    The header sniff runs first, so a generated file with long lines reports
    ``generated-header``.
    """
    if has_generated_header(path):
        return REASON_HEADER
    if is_long_line_artifact(path):
        return REASON_LONG_LINES
    return None
