"""Tests for lib/generated_files.py: the header sniff and long-line detector."""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from lib.generated_files import (  # noqa: E402
    LONG_LINE_THRESHOLD,
    matches_generated_name,
    average_line_length,
    generated_reason,
    has_generated_header,
    is_long_line_artifact,
)


@pytest.mark.parametrize("marker", [
    "-- GENERATED FILE - DO NOT EDIT",
    "// Code generated by protoc-gen-go. DO NOT EDIT.",
    "# @generated by buck",
    "/* This file is auto-generated */",
    "// AUTOGENERATED - regenerate with make",
    "// AUTO-GENERATED by tool",
    "# auto generated from schema.yaml",
    "// do not edit: owned by the schema tool",
])
def test_generated_header_markers_match_case_insensitively(tmp_path, marker):
    f = tmp_path / "x.sql"
    f.write_text(f"{marker}\nSELECT 1;\n")
    assert has_generated_header(f) is True
    assert generated_reason(f) == "generated-header"


@pytest.mark.parametrize("line", [
    "generated file whose name looks ordinary, such as a schema dump",
    "Writes the generated file; do not edit it by hand, rerun make.",
    "    return render(autogenerated=True)",
])
def test_generated_header_prose_without_comment_leader_is_ignored(tmp_path, line):
    f = tmp_path / "codegen.py"
    q = '"' * 3
    f.write_text(q + "Codegen driver.\n\n" + line + "\n" + q + "\n")
    assert has_generated_header(f) is False


@pytest.mark.parametrize("first_line,expected", [
    ('"""Writes the generated file for the API client."""', False),
    ("# Loads the generated file and patches it", False),
    ("-- GENERATED FILE - regenerate with make schema", True),
    ("/* Generated file */", True),
    ("# === GENERATED FILE ===", True),
])
def test_generated_header_generated_file_only_as_banner(tmp_path, first_line, expected):
    f = tmp_path / "x.py"
    f.write_text(first_line + "\nA = 1\n")
    assert has_generated_header(f) is expected


def test_long_line_small_file_skips_read(tmp_path, monkeypatch):
    f = tmp_path / "small.py"
    f.write_text("x = 1\n")
    import lib.generated_files as mod
    monkeypatch.setattr(mod, "average_line_length",
                        lambda p: (_ for _ in ()).throw(AssertionError("read")))
    assert mod.is_long_line_artifact(f) is False


def test_generated_header_markdown_bullet_is_not_a_comment(tmp_path):
    f = tmp_path / "CHANGELOG.md"
    f.write_text("Release notes\n\n* Auto-generated release notes now include PRs\n"
                 "* Do not edit this table by hand\n")
    assert has_generated_header(f) is False


def test_generated_header_markdown_heading_is_not_a_comment(tmp_path):
    md = tmp_path / "guide.md"
    md.write_text("# Do not edit these by hand\n\n## Auto-generated sections\n")
    assert has_generated_header(md) is False
    marked = tmp_path / "api.md"
    marked.write_text("<!-- DO NOT EDIT: generated by docgen -->\n# API\n")
    assert has_generated_header(marked) is True


def test_generated_header_after_utf8_bom_matches(tmp_path):
    f = tmp_path / "Client.cs"
    f.write_bytes("\ufeff// <auto-generated/>\nclass C {}\n".encode("utf-8"))
    assert has_generated_header(f) is True


def test_generated_header_jsdoc_and_docstring_leaders_match(tmp_path):
    js = tmp_path / "a.js"
    js.write_text("/**\n * @generated\n */\nexport const a = 1;\n")
    py = tmp_path / "b.py"
    q = '"' * 3
    py.write_text(q + "Autogenerated by schema2py." + q + "\nA = 1\n")
    assert has_generated_header(js) is True
    assert has_generated_header(py) is True


def test_generated_header_on_line_five_matches(tmp_path):
    f = tmp_path / "x.py"
    f.write_text("a = 1\nb = 2\nc = 3\nd = 4\n# DO NOT EDIT\ne = 5\n")
    assert has_generated_header(f) is True


def test_generated_header_after_a_long_first_line_matches(tmp_path):
    f = tmp_path / "bundle.js"
    f.write_text("var a = '" + "x" * 100_000 + "';\n// @generated by bundler\nvar b = 1;\n")
    assert has_generated_header(f) is True


def test_generated_header_after_line_five_is_ignored(tmp_path):
    f = tmp_path / "hand.py"
    body = ["def route(x):"] + [f"# note {i}" for i in range(198)]
    body.append("# do not edit the routing table above without updating the docs")
    f.write_text("\n".join(body) + "\n")
    assert has_generated_header(f) is False
    assert generated_reason(f) is None


def test_generated_header_unreadable_file_is_not_excluded(tmp_path):
    assert has_generated_header(tmp_path / "missing.sql") is False
    assert generated_reason(tmp_path / "missing.sql") is None


def test_long_line_payload_is_excluded(tmp_path):
    f = tmp_path / "font.ts"
    f.write_text('export const FONT = "' + "A" * 40000 + '";\nexport default FONT;\n')
    assert average_line_length(f) > 20000
    assert is_long_line_artifact(f) is True
    assert generated_reason(f) == "long-lines"


def test_long_line_threshold_keeps_wide_hand_written_code(tmp_path):
    f = tmp_path / "wide.py"
    f.write_text("\n".join(["    x = x + 1  # " + "p" * 85] * 20) + "\n")
    assert 90 < average_line_length(f) < 110
    assert is_long_line_artifact(f) is False


def test_long_line_threshold_calibration_band():
    # Above a JSONL fixture (296 chars/line, kept), below a hand-built
    # HTML explainer page with inline data (3,817 chars/line, excluded).
    assert 296 < LONG_LINE_THRESHOLD < 3817  # strict: is_long_line_artifact uses >


def test_long_line_measures_characters_not_bytes(tmp_path):
    f = tmp_path / "cjk.py"
    f.write_text("\n".join(["# " + "\u6f22" * 600] * 3) + "\n", encoding="utf-8")
    assert average_line_length(f) < LONG_LINE_THRESHOLD
    assert is_long_line_artifact(f) is False


def test_long_line_counts_unterminated_last_line(tmp_path):
    f = tmp_path / "one.txt"
    f.write_bytes(b"abcd")
    assert average_line_length(f) == 4.0
    assert average_line_length(tmp_path / "gone.txt") == 0.0


def test_generated_header_sniff_spares_its_own_module():
    """The module documents the markers; they must stay out of its first lines."""
    import lib.generated_files as mod
    assert has_generated_header(Path(mod.__file__)) is False
    assert generated_reason(Path(mod.__file__)) is None


def test_long_line_average_uses_capped_head(tmp_path):
    f = tmp_path / "big.txt"
    # ~1.6 MB: a short-line first 1 MB followed by one enormous final line.
    f.write_text(("y" * 99 + "\n") * 10500 + "z" * 600000)
    assert average_line_length(f) < LONG_LINE_THRESHOLD



@pytest.mark.parametrize("path,expected", [
    ("web/src/database.types.ts", True),
    ("api.generated.ts", True),
    ("schema.generated.sql", True),
    ("client.gen.ts", True),
    ("src/types.ts", False),
    ("generated/readme.md", False),
])
def test_generated_header_free_name_patterns(path, expected):
    assert matches_generated_name(path) is expected
