"""Tests for lib/generated_files.py: the header sniff and long-line detector."""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from lib.generated_files import (  # noqa: E402
    LONG_LINE_THRESHOLD,
    average_line_length,
    generated_reason,
    has_generated_header,
    is_long_line_artifact,
)


@pytest.mark.parametrize("marker", [
    "-- GENERATED FILE - DO NOT EDIT",
    "// Code generated by protoc-gen-go. DO NOT EDIT.",
    "# @generated by buck",
    "/* This file is auto-generated */",
    "// AUTOGENERATED - regenerate with make",
    "// AUTO-GENERATED by tool",
    "# auto generated from schema.yaml",
    "// do not edit: owned by the schema tool",
])
def test_generated_header_markers_match_case_insensitively(tmp_path, marker):
    f = tmp_path / "x.sql"
    f.write_text(f"{marker}\nSELECT 1;\n")
    assert has_generated_header(f) is True
    assert generated_reason(f) == "generated-header"


def test_generated_header_on_line_five_matches(tmp_path):
    f = tmp_path / "x.py"
    f.write_text("a = 1\nb = 2\nc = 3\nd = 4\n# DO NOT EDIT\ne = 5\n")
    assert has_generated_header(f) is True


def test_generated_header_after_line_five_is_ignored(tmp_path):
    f = tmp_path / "hand.py"
    body = ["def route(x):"] + [f"# note {i}" for i in range(198)]
    body.append("# do not edit the routing table above without updating the docs")
    f.write_text("\n".join(body) + "\n")
    assert has_generated_header(f) is False
    assert generated_reason(f) is None


def test_generated_header_unreadable_file_is_not_excluded(tmp_path):
    assert has_generated_header(tmp_path / "missing.sql") is False
    assert generated_reason(tmp_path / "missing.sql") is None


def test_long_line_payload_is_excluded(tmp_path):
    f = tmp_path / "font.ts"
    f.write_text('export const FONT = "' + "A" * 40000 + '";\nexport default FONT;\n')
    assert average_line_length(f) > 20000
    assert is_long_line_artifact(f) is True
    assert generated_reason(f) == "long-lines"


def test_long_line_threshold_keeps_wide_hand_written_code(tmp_path):
    f = tmp_path / "wide.py"
    f.write_text("\n".join(["    x = x + 1  # " + "p" * 85] * 20) + "\n")
    assert 90 < average_line_length(f) < 110
    assert is_long_line_artifact(f) is False


def test_long_line_threshold_calibration_band():
    # Above a JSONL fixture (296 chars/line), at or below a hand-built HTML
    # explainer page (3,817 chars/line).
    assert 296 < LONG_LINE_THRESHOLD <= 3817


def test_long_line_measures_characters_not_bytes(tmp_path):
    f = tmp_path / "cjk.py"
    f.write_text("\n".join(["# " + "\u6f22" * 600] * 3) + "\n", encoding="utf-8")
    assert average_line_length(f) < LONG_LINE_THRESHOLD
    assert is_long_line_artifact(f) is False


def test_long_line_counts_unterminated_last_line(tmp_path):
    f = tmp_path / "one.txt"
    f.write_bytes(b"abcd")
    assert average_line_length(f) == 4.0
    assert average_line_length(tmp_path / "gone.txt") == 0.0


def test_generated_header_sniff_spares_its_own_module():
    """The module documents the markers; they must stay out of its first lines."""
    import lib.generated_files as mod
    assert has_generated_header(Path(mod.__file__)) is False
