"""
Per-skill configuration for the standalone skill ZIP build pipeline.

Each entry in SKILLS maps a skill name to:
  standalone_name        — name field written into the ZIP's SKILL.md frontmatter
  standalone_description — description field (trigger-phrased for description-based
                           auto-matching; no plugin namespacing). The current
                           plugin version + release URL are appended automatically
                           at build time so users see which version they installed
                           in the Skills UI and know where to check for updates.
  source_dir             — path relative to repo root
  replacements           — dict mapping chat-replace:KEY → replacement text
  exclude_dirs           — subdirectories omitted from the ZIP
  bundle_files           — optional dict mapping ZIP-relative dest paths → source
                           paths (relative to repo root). Markdown files have their
                           YAML frontmatter stripped during bundling.
"""

import json
from pathlib import Path


def _plugin_version() -> str:
    """Read the canonical version from .claude-plugin/plugin.json.

    Standalone descriptions append this so users see the installed version
    in the Skills UI and can compare against the latest release. Single
    source of truth — drift impossible.
    """
    plugin_json = Path(__file__).parent.parent / ".claude-plugin" / "plugin.json"
    return json.loads(plugin_json.read_text("utf-8"))["version"]


VERSION = _plugin_version()
RELEASES_URL = "https://github.com/bjcoombs/ai-native-toolkit/releases"
VERSION_SUFFIX = (
    f" Standalone build v{VERSION} — check {RELEASES_URL} for updates and "
    "use the Skills UI's Replace option to upgrade in place."
)


SKILLS: dict[str, dict] = {
    "assess": {
        "standalone_name": "assess",
        "standalone_description": (
            "Assess a codebase's AI-agent readiness (0-8 layered contract model spanning "
            "navigability, runtime liveness, and the write-side gates) and generate a complexity "
            "hotspot SVG and a doc-navigability graph SVG. TRIGGER when asked for an AI-readiness "
            "review, codebase assessment, complexity heatmap, doc navigability/connectivity map, "
            "migration risk triage, or 'how ready is this code for agents?'. Full script "
            "automation (SVGs, deterministic core) requires terminal access; the layered "
            "assessment works in any context."
            + VERSION_SUFFIX
        ),
        "source_dir": "skills/assess",
        "exclude_dirs": {"tests", "__pycache__", ".pytest_cache", ".venv"},
        "replacements": {
            "uv-treemap": (
                'uv run scripts/complexity-treemap.py "$REPO_ROOT" '
                '-o "$REPO_ROOT/.assess/complexity-heatmap.svg" '
                '--stats "$REPO_ROOT/.assess/complexity-stats.json"'
            ),
            "uv-doc-graph": (
                'uv run scripts/doc-graph-svg.py "$REPO_ROOT" '
                '-o "$REPO_ROOT/.assess/doc-graph.svg"'
            ),
            "uv-treemap-overlay": (
                'uv run scripts/complexity-treemap.py "$REPO_ROOT" '
                '-o "$REPO_ROOT/.assess/complexity-heatmap.svg" '
                '--stats "$REPO_ROOT/.assess/complexity-stats.json" '
                '--test-pressure "$REPO_ROOT/.assess/run-context.json"'
            ),
            "uv-core": 'uv run scripts/assess_core.py "$REPO_ROOT"',
            "uv-finalize": 'uv run scripts/assess_finalize.py "$REPO_ROOT"',
            "uv-emit-workflow": 'uv run scripts/assess_emit_workflow.py "$REPO_ROOT"',
            "treemap-exclude-example": (
                'uv run scripts/complexity-treemap.py "$REPO_ROOT" '
                "--exclude regulatory-raw --exclude vetted-context "
                "--exclude '*.csv'"
            ),
            "report-footer": (
                "_Report generated by "
                "[assess](https://github.com/bjcoombs/ai-native-toolkit)._"
            ),
            "pr-footer": (
                "_Generated by "
                "[assess](https://github.com/bjcoombs/ai-native-toolkit)._"
            ),
            # The orchestrator delegates layer-scoring, report-writing, and the
            # end-of-run offers to an agent + two sub-skills in plugin mode. This
            # standalone build has no sub-agents or sub-skills, so each delegation
            # line is swapped for a "read the bundled methodology and apply it
            # inline" instruction; the unit bodies ride along under references/.
            "layer-scorer-delegate": (
                "Read the bundled methodology at `references/assess-layer-scorer.md` "
                "and apply it yourself to produce the 0-8 score, the per-layer "
                "verdicts with evidence, and the maturity label - this context has "
                "no separate agent. Hold that scorecard for the report step."
            ),
            "findings-delegate": (
                "Read the bundled `references/assess-findings.md` and follow it "
                "inline, using the scorecard from the layer-scoring step, to "
                "assemble `.assess/assess-report.md` from the data bus: the verbatim "
                "findings section, the lying signals, and the mandatory Top 3 Actions."
            ),
            "pr-delegate": (
                "Read the bundled `references/assess-pr.md` and follow it inline for "
                "the end-of-run offers (PR, issue tracking, freeze-into-CI) and the "
                "tool-feedback prompt, reading the written `.assess/assess-report.md`."
            ),
        },
        # Bundle the decomposed units inside the ZIP so standalone-mode runs can
        # Read them via relative paths. In plugin mode these are a real agent
        # (agents/) and two sub-skills (skills/); standalone has neither, so the
        # bodies travel with the skill and the delegation lines (above) point at
        # them. Bundled markdown is frontmatter-stripped and marker-transformed,
        # so their own chat-skip/chat-replace blocks resolve like the main SKILL.
        "bundle_files": {
            "references/assess-layer-scorer.md": "agents/assess-layer-scorer.md",
            "references/assess-findings.md": "skills/assess-findings/SKILL.md",
            "references/assess-pr.md": "skills/assess-pr/SKILL.md",
        },
    },
    "huddle": {
        "standalone_name": "huddle",
        "standalone_description": (
            "Structured multi-perspective analysis using Six Thinking Hats. TRIGGER when asked "
            "to run a huddle, wanting multi-perspective or red-team/blue-team analysis, needing "
            "to weigh a hard decision from several angles, or wanting panel/board deliberation. "
            "Scales from solo gut-check (1) to board-level deliberation (8+) using Fibonacci "
            "team sizing. Team mode with persistent agents requires the Claude Code CLI."
            + VERSION_SUFFIX
        ),
        "source_dir": "skills/huddle",
        "exclude_dirs": set(),
        "replacements": {
            "hat-source": (
                "**Hat methodologies** (`white-hat`, `red-hat`, `black-hat`, "
                "`yellow-hat`, `green-hat`, `blue-hat`) are bundled inside this "
                "skill at `hats/<hat>-hat.md`. Spawn prompts instruct sub-agents "
                "to `Read('hats/<hat>-hat.md')` before applying the methodology "
                "— this is how a fresh-context sub-agent learns the hat without "
                "depending on Claude-Code-only agent infrastructure."
            ),
            "phased-spawn-instructions": (
                "   - The hat methodology for this phase: instruct the sub-agent "
                "to call `Read('hats/<hat>-hat.md')` (relative to the skill root) "
                "and apply that methodology"
            ),
            "capability-detection": (
                "**This standalone build runs phased sub-agent mode for size 2+.** "
                "Team mode (persistent agents with cross-talk) is only available "
                "in the Claude Code CLI and is not reachable from here. Tell the "
                "user one line: \"Running in phased sub-agent mode (N lenses, M "
                "phases — standalone build, team mode not available).\""
            ),
            "branch-phased-row": "| Size 2+ | **Phased Sub-Agent Mode** (below) |",
            "execution-mode-rule": (
                "Two execution modes are reachable in this standalone build. "
                "Pick one deterministically: team size = 1 → solo flat-parallel; "
                "team size ≥ 2 → phased sub-agent mode. Team mode (persistent "
                "agents with cross-talk) is only available in the Claude Code CLI "
                "and is not reachable from here."
            ),
            "team-mode-row": (
                "| **Team mode** | Size 2+, Claude Code only | Persistent agents "
                "with cross-talk — not available in standalone context | — |"
            ),
        },
        # Bundle the hat methodology files inside the ZIP so standalone-mode
        # sub-agents can read them via relative paths. Without this they'd
        # depend on `~/.claude/agents/*-hat.md` which only exists in plugin
        # installs.
        "bundle_files": {
            "hats/white-hat.md": "agents/white-hat.md",
            "hats/red-hat.md": "agents/red-hat.md",
            "hats/black-hat.md": "agents/black-hat.md",
            "hats/yellow-hat.md": "agents/yellow-hat.md",
            "hats/green-hat.md": "agents/green-hat.md",
            "hats/blue-hat.md": "agents/blue-hat.md",
        },
    },
    "skill-forge": {
        "standalone_name": "skill-forge",
        "standalone_description": (
            "Harden a skill (draft or existing) through judge-panel refinement rounds until it "
            "clears a 3-tier promotion gate, then promote it. A quality gate that runs after "
            "authoring, not an authoring tool. TRIGGER when asked to test/harden/forge/prove a "
            "skill, wanting a skill driven through adversarial rounds before shipping, asking 'is "
            "this skill ready?', or wanting a skill quality-gated by a judge panel. Team mode "
            "with persistent judges requires the Claude Code CLI; this build runs solo."
            + VERSION_SUFFIX
        ),
        "source_dir": "skills/skill-forge",
        "exclude_dirs": {"tests", "__pycache__", ".pytest_cache", ".venv"},
        "replacements": {
            "execution-mode-rule": (
                "Run in solo mode: a single agent plays all three roles - runner, panel, "
                "and lead - in one context, applying the draft to each test case, judging "
                "every transcript through each lens, then amending one thing, round by round "
                "until the gate promotes or the budget ceiling stops it."
            ),
        },
    },
    "deslop": {
        "standalone_name": "deslop",
        "standalone_description": (
            "Detect and remove the telltale signs of AI-generated 'slop' from any written "
            "text — articles, reports, emails, essays, bios, marketing copy, documentation, "
            "or anything meant to read as if a thoughtful human wrote it. TRIGGER when asked "
            "to 'make this sound less like AI', 'remove the AI tells', 'de-slop this', 'check "
            "if this reads as AI-written', 'make it sound human', 'edit out the ChatGPT voice', "
            "or when a draft is critiqued as generic, puffy, or robotic. Also apply as a silent "
            "quality gate before finalizing substantial prose. Based on Wikipedia's 'Signs of "
            "AI writing' field guide."
            + VERSION_SUFFIX
        ),
        "source_dir": "skills/deslop",
        # Pure-markdown skill, portable as-is: no plugin path resolution,
        # $ARGUMENTS, namespaced slash commands, or Claude-Code-only tools to
        # strip, so no chat-skip/chat-replace markers and no replacements.
        "exclude_dirs": set(),
        "replacements": {},
    },
    "ab-equivalence": {
        "standalone_name": "ab-equivalence",
        "standalone_description": (
            "Compare two versions of an LLM-directed document - an original (teacher) and a "
            "candidate (student) - across a transfer set and return a per-case "
            "behavioural-equivalence verdict plus an efficiency signal. A transform-agnostic "
            "library capability other skills compose to gate a transform on behavioural sameness. "
            "TRIGGER when asked to A/B test two versions of a prompt, instruction, or skill, to "
            "check whether a rewritten or compressed document still behaves the same as the "
            "original, to validate behavioural equivalence between two document versions, or to "
            "gate a transform on no-regression. This standalone build runs solo mode only; "
            "phased sub-agent and team modes require the Claude Code CLI."
            + VERSION_SUFFIX
        ),
        "source_dir": "skills/ab-equivalence",
        "exclude_dirs": {"tests", "__pycache__", ".pytest_cache", ".venv"},
        "replacements": {
            "execution-mode-rule": (
                "This standalone build runs solo mode only: a single agent works each case "
                "sequentially - applying the original and candidate via the runner wrapper, "
                "then judging the two transcripts with the equivalence-judge prompt to record "
                "the per-case verdict and efficiency signal. Phased sub-agent and team modes "
                "require the Claude Code CLI and are not available here."
            ),
        },
    },
    "semantic-compress": {
        "standalone_name": "semantic-compress",
        "standalone_description": (
            "Make an LLM-directed document smaller while preserving what it does. Point at core "
            "knowledge the model already holds (a concept name activates it) and keep "
            "project-specific detail explicit and verbatim. TRIGGER when asked to compress, "
            "tighten, shorten, or strip a prompt or instruction meant for an LLM, when an "
            "instruction set explains concepts the model already knows from training, or when "
            "reducing token cost of an LLM-directed prompt without losing meaning. Not for "
            "human-facing prose. This standalone build runs Local Mode (span-level core->pointer) "
            "only; Distill Mode (A/B-validated whole-document compression) requires the runner "
            "harness available in the Claude Code CLI."
            + VERSION_SUFFIX
        ),
        "source_dir": "skills/semantic-compress",
        # Distill mode references the runner harness + skill-forge's A/B
        # equivalence capability (plugin-only). The chat-replace swaps the
        # distill-availability line for an honest degrade note so the ZIP states
        # distill mode needs the Claude Code CLI; Local Mode ships unchanged. The
        # distill reference docs (distill-loop, transfer-set-design,
        # distillation-report-template) ride along under references/; their
        # team/subagent spawn mechanics are wrapped in chat-skip so only the
        # methodology survives, never a Claude-Code-only tool.
        "exclude_dirs": {"tests", "__pycache__", ".pytest_cache", ".venv"},
        "replacements": {
            "distill-availability": (
                "**Distill mode is not available in this standalone build.** It requires the "
                "runner harness - subagents plus `skill-forge`'s A/B equivalence capability - "
                "reachable only in the Claude Code CLI plugin. This build runs **Local Mode** "
                "only. To distill a whole document or skill against an A/B "
                "behavioural-equivalence gate, run `semantic-compress` from the Claude Code "
                "plugin."
            ),
        },
    },
}
