"""
Per-skill configuration for the standalone skill ZIP build pipeline.

Each entry in SKILLS maps a skill name to:
  standalone_name        — name field written into the ZIP's SKILL.md frontmatter
  standalone_description — description field (trigger-phrased for description-based
                           auto-matching; no plugin namespacing)
  source_dir             — path relative to repo root
  replacements           — dict mapping chat-replace:KEY → replacement text
  exclude_dirs           — subdirectories omitted from the ZIP
"""

SKILLS: dict[str, dict] = {
    "assess": {
        "standalone_name": "assess",
        "standalone_description": (
            "Assess a codebase's AI-agent readiness (0-7 layered contract model) and generate "
            "a complexity hotspot SVG treemap. TRIGGER when asked for an AI-readiness review, "
            "codebase assessment, complexity heatmap, migration risk triage, or 'how ready is "
            "this code for agents?'. Full script automation (SVG, deterministic core) requires "
            "terminal access; the layered assessment works in any context."
        ),
        "source_dir": "skills/assess",
        "exclude_dirs": {"tests", "__pycache__", ".pytest_cache", ".venv"},
        "replacements": {
            "uv-treemap": (
                'uv run scripts/complexity-treemap.py "$REPO_ROOT" '
                '-o "$REPO_ROOT/.assess/complexity-heatmap.svg" '
                '--stats "$REPO_ROOT/.assess/complexity-stats.json"'
            ),
            "uv-core": 'uv run scripts/assess_core.py "$REPO_ROOT"',
            "uv-finalize": 'uv run scripts/assess_finalize.py "$REPO_ROOT"',
            "report-footer": (
                "_Report generated by "
                "[assess](https://github.com/bjcoombs/ai-native-toolkit)._"
            ),
            "pr-footer": (
                "_Generated by "
                "[assess](https://github.com/bjcoombs/ai-native-toolkit)._"
            ),
        },
    },
    "huddle": {
        "standalone_name": "huddle",
        "standalone_description": (
            "Structured multi-perspective analysis using Six Thinking Hats. TRIGGER when asked "
            "to run a huddle, wanting multi-perspective or red-team/blue-team analysis, needing "
            "to weigh a hard decision from several angles, or wanting panel/board deliberation. "
            "Scales from solo gut-check (1) to board-level deliberation (8+) using Fibonacci "
            "team sizing. Team mode with persistent agents requires Claude Code."
        ),
        "source_dir": "skills/huddle",
        "exclude_dirs": set(),
        "replacements": {},
    },
}
